<%@ Page Title="addtoCart" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="addtoCart.aspx.cs" Inherits="CakeWebManagement.addtoCart" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    
    <style>
        #MainContent_GridView1 a {
  background: #625d5d;
  padding: 10px;
  color: white;
  border-radius: 4px;
}
        th{
            background: #625d5d;
            color: white;
        }
    </style>
    <section>
        
        <div class="container">
            <div class="col-md-12">

           <h3>Your SHopping Cart.</h3>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"   
                    DataKeyNames="id" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                    onrowupdating="GridView1_RowUpdating" CellSpacing="2" CssClass="table" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">   
            <Columns>
                <asp:BoundField HeaderText="Cart Id" DataField="id" ReadOnly="true"/>
                <asp:BoundField HeaderText="Name" DataField="labelP" ReadOnly="true"/>

                <asp:TemplateField HeaderText="Price">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("priceP") %>' ReadOnly="true"></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("priceP") %>'></asp:Label>  
                            </ItemTemplate>  
               </asp:TemplateField> 

                <%--<asp:BoundField HeaderText="Price" DataField="priceP" />--%>
                <%--<asp:BoundField HeaderText="QTY" DataField="qtyP" />--%>
                <asp:TemplateField HeaderText="Quantity">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("qtyP") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("qtyP") %>'></asp:Label>  
                            </ItemTemplate>  
               </asp:TemplateField> 
            </Columns>
        </asp:GridView>
    </div>
    </div>
        
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h3>Total:</h3>
                    <asp:Label ID="totalprice" runat="server" Text="Label"></asp:Label>

                </div>
                <div class="col-md-6">
                    <asp:Button ID="Button1" runat="server" Text="Check Out" />

                </div>
            </div>
        </div>
    </section>
   
</asp:Content>
